## Assignment 1 | Data Types

Add code cells as needed for your answers. 

### Exercise 1: Manipulating Lists

Create a list containing the numbers 10, 20, and 30. Store your list as a variable named `a`. Then create a second list containing the numbers 30, 60, and 90. Call this this `b`.

In [1]:
#creating a list called 'a'
a = [10, 20, 30]

In [2]:
#creating a second list called 'b'
b = [30, 60, 90]

In the cells below, write Python expressions to create the following four outputs by combining `a` and `b` in creative ways:

1. [[10, 20, 30], [30, 60, 90]]

2. [10, 20, 30, 30, 60, 90]

3. [10, 20, 60, 90]

4. [20, 40, 60]

In [4]:
#1. expression to combine a and b in creative ways: [[10, 20, 30], [30, 60, 90]]
[a] + [b]

[[10, 20, 30], [30, 60, 90]]

In [5]:
#2. expression to combine a and b in creative ways: [10, 20, 30, 30, 60, 90]
a + b

[10, 20, 30, 30, 60, 90]

In [34]:
#3. expression to combine a and b in creative ways: [10, 20, 60, 90]
c = a + b
del c[2:4]
c

[10, 20, 60, 90]

In [46]:
#4. expression to combine a and b in creative ways: [20, 40, 60]
result = map(lambda x,y: y-x, a,b)
print(list(result))

[20, 40, 60]


### Exercise 2. Working with Lists

Create a list that contains the sums of each of the lists in G. 

`G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]`

Your output should look like:

- `[30, 32, 34, 34]`

Hint: try computing the sum for just one list first.

In [54]:
#create list called G 
G = [[13, 9, 8], [14, 6, 12], [10, 13, 11], [7, 18, 9]]

#use map function to sum individual items within each sublist
list(map(sum, G))

[30, 32, 34, 34]

### Exercise 3: String Manipulation

Turn the string below into 'all good countrymen' using the minimum amount of code, using only the methods we've covered so far. A couple of lines of code should do the trick.  Note: this requires string and list methods.

In [ ]:
s = 'Now is the time for all good men to come to the aid of their country!'

'.....'

### Exercise 4: String Manipulation and Type Conversion

Define a variable `a = "Sarah earns $96500 in a year"`. Then maniuplate the value of `a` in order to print the following string: `Sarah earns $8041.67 monthly`

Start by doing it in several steps and then combine them one step at a time until you can do it in one line.

In [14]:
#defining variable
a = "Sarah earns $96500 in a year"

#print the function a but replace individual text/numbers in the string. Not sure I did this how it was intended? 
print(a.replace("$96500 in a year", "$8041.67 in a month"))

Sarah earns $8041.67 in a month


### Exercise 5: Create and Query a Dictionary on State Demographics

Create two dictionaries, one for California and one for New York state, based on the data in the following table:

| States | Pop Density | Prop White | Prop Afr Amer | Prop Asian | Prop Other | Owners | Renters |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| CA | 239.1 | 0.57  | 0.06 | 0.13 | 0.22 | 7035371 | 5542127 |
| NY | 411.2 | 0.65  | 0.15 | 0.07 | 0.22 | 3897837 | 3419918 |

Each dictionary should have the following keys and value types: `name: (string)` , `population density: (float)`, `race (dict)`, `tenure: (dict)`. 

1.  Create one dictionary called CA and one called NY that contain dictionaries containing name, pop_density, race as a dictionary, and tenure for California and New York.  Now combine these into a dictionary called "states", making it a dictionary of dictionaries, or a nested dictionary.

1.  Check if Texas is in our state dictionary (we know it isn't but show us).

1. Print the White population in New York as a percentage

1. Assume there was a typo in the data, and update the White population fraction of NY to 0.64. Verify that it was updated by printing the percentage again.

1. Print the percentage of households that are renters in California, with two decimal places

In [ ]:
#idkkkkk

### Exercise 6: Working with Numpy Arrays

1. Create and print a 4 x 4 array named `a` with value 3 everywhere.

1. Create and print a 4 x 4 array named `b` with elements drawn from a uniform random distribution 

1. Create and print array `c` by dividing a by b

1. Compute and print the min, mean, max, median, and 90th percentile values of `c`

1. Compute and print the sum of the second column in `c`

In [18]:
#imports module numpy and renames it np
import numpy as np

#Create an array called a_array and print a 4 x 4 array named a with value 3 everywhere.
a_array = np.array([[3,3,3,3], [3,3,3,3], [3,3,3,3], [3,3,3,3]])
print(a_array)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [22]:
#Create and print a 4 x 4 array named b with elements drawn from a uniform random distribution
b_array = np.random.uniform(size =(4,4), low = 0, high = 1) 
b_array

array([[0.94858469, 0.43554171, 0.25163559, 0.23434041],
       [0.25608117, 0.07535409, 0.25560117, 0.01637042],
       [0.48580448, 0.49989599, 0.00175751, 0.64028494],
       [0.41895216, 0.06734206, 0.8720998 , 0.61679014]])

In [24]:
#Create and print array c by dividing a by b
c = np.divide(a_array, b_array)
c

array([[   3.1626064 ,    6.88797398,   11.92200219,   12.80188911],
       [  11.71503569,   39.81204204,   11.73703547,  183.25740795],
       [   6.17532385,    6.00124837, 1706.95618   ,    4.68541397],
       [   7.16072217,   44.5486804 ,    3.43997328,    4.86389098]])

In [30]:
#Compute and print the min, mean, max, median, and 90th percentile values of c
#min
np.min(c)

3.162606402147044

In [31]:
#mean
np.mean(c)

129.07046411536146

In [29]:
#max
np.max(c)

1706.9561800027777

In [32]:
#median
np.median(c)

9.437878929532225

In [35]:
#90th percentile
np.percentile(c, 90)

113.90304417163227

In [36]:
#Compute and print the sum of the second column in c by importing pandas first
import pandas as pd 

In [39]:
# create a data frame from our array
df = pd.DataFrame(c, columns = ['C1', 'C2', 'C3', 'C4'])
print(df)

          C1         C2           C3          C4
0   3.162606   6.887974    11.922002   12.801889
1  11.715036  39.812042    11.737035  183.257408
2   6.175324   6.001248  1706.956180    4.685414
3   7.160722  44.548680     3.439973    4.863891


In [41]:
#create a new function that sums only the second column
column_c_total = df['C2'].sum()
print(column_c_total)

97.24994479036143
